name: run-unit-tests-pal-lab

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MLX & Nanobind
        run: pip install --no-deps "git+https://github.com/TheProxyCompany/mlx.git" "nanobind==2.5.0"
      - name: Python deps
        run: pip install "."
      - name: Verify MLX and Metal version
        run: |
          python -c "import mlx.core as mx; print(f'Default device: {mx.default_device()}');"
      - name: Unit tests
        run: pytest tests/ -v --tb=short
